name: wde-explorer
version: git
summary: Windows-like file explorer
description: |
  WDE Explorer is a file explorer similar to the Windows Explorer.
  This is only a test if it is possible to publish this app to the 
  snapcraft store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  wde-explorer:
    command: wde-explorer

parts:
  wde-explorer:
    source: .
    plugin: rust
    build-attributes: [no-system-libraries]
    build-packages:
      - libudev-dev
      - libssl-dev
      - make
      - cmake
      - pkg-config
      - libfreetype6-dev
    stage-packages:
      - libssl1.0.0
      - libudev1
      - libstdc++6
      - libfreetype6
      
